In [1]:
import os
import numpy as np

You can run terminal commands in a Jupyter notebook by prefacing them with `!`. This will untar the `data/` directory:

In [2]:
!tar -xzf data.tgz

# building an `enterprise` model

The main purpose of `enterprise` is to generate the PTA **likelihood** function.
Then you can use that function to do whatever you want.

The multivariat Gaussian likelihood is defined:
$$\mathcal{L} = \left(2\pi\, \det\mathbb{C} \right)^{-1/2} \,\, \exp\left( -\frac{1}{2} \vec{q}\cdot \mathbb{C}^{-1} \cdot \vec{q} \right)$$
where $\mathbb{C}$ is the covariance matrix and $\vec{q}$ is the residual vector.

In the PTA case, we construct $\mathbb{C}$ from white noise covariance $\mathbb{N}$, the design matrix of for the Gaussian process (GP) models $\mathbb{T}$, and the prior for the GP coefficients $\mathbb{B}$.
The residual vector contains the TOA residuals, $\delta\vec{t}$, and any deterministic signals in the model, $\vec{s}$, (e.g. a continuous GW from a single SMBHB).

$$ \mathbb{C} = \mathbb{N} + \mathbb{TBT}^T $$
$$ \vec{q} = \delta\vec{t} - \vec{s} $$



While the likelihood is always a multivariate Gaussian likelihood, the details will depend on the particulars of the  model.
`enterprise` is set up so that you specify the **data**, **model**, and **model parameters**, then it constructs the covariance matrix and residual vector needed to calculate the likelihood for a given set of parameters.  The `enterprise` parameter specification is based on the **prior** for each parameter.

The `enterprise.signals.signal_base.PTA` object has two commonly used methods:
* `PTA.get_lnlikelihood()`
* `PTA.get_lnprior()`

each takes a parameter vector (list or dict of parameter values) as an input.
These two methods are commonly passed to a **Markov chain Monte Carlo** (MCMC) sampler in order to draw samples from the model posterior probability distribution.

The `enterprise.signals` module contains nearly everything we need to construct the data model and get our likelihood and prior functions.

## load data

The `data/` directory contains `.par` and `.tim` files for three pulsars, one from each recent PTA dataset:
* J1600-3053 from EPTA 6 pulsar
* J2241-5236 from PPTA DR2
* J2317+1439 from NANOGrav 12.5 yr

Each PTA uses a slightly different data model, so these three will give us an introductory walkthrough of what we can do with `enterprise`.

To keep things organized here's a dictionary of the filenames for each pulsar:

In [3]:
datafiles = {
    "J1600-3053":{"par":"J1600-3053_EPTA_6psr.par", "tim":"J1600-3053_EPTA_6psr.tim"},
    "J2241-5236":{"par":"J2241-5236_PPTA_dr2.par", "tim":"J2241-5236_PPTA_dr2.tim"},
    "J2317+1439":{"par":"J2317+1439_NANOGrav_12y.par", "tim":"J2317+1439_NANOGrav_12y.tim"},
}

Let's load the data for J2317+1439 as an `enterprise.pulsar.Pulsar` object and construct its model

In [4]:
from enterprise.pulsar import Pulsar

In [5]:
datadir = os.path.abspath("data")

In [6]:
pfile = os.path.join(datadir, datafiles['J2317+1439']['par'])
tfile = os.path.join(datadir, datafiles['J2317+1439']['tim'])

psr = Pulsar(pfile, tfile)

[tempo2Util.C:396] Warning: [MISC1] Unknown parameter in par file:  DMX
[tempo2Util.C:401] Warning: [DUP1] duplicated warnings have been suppressed.

[tempo2Util.C:396] Warning: [PAR2] Have not set a DM epoch. The period epoch will be used instead. J2317+1439_NANOGrav_12y.par
[tempo2Util.C:396] Warning: [TIM1] Please place MODE flags in the parameter file 
[observatory.C:271] Warning: Assuming site '3' means 'ao'


(the warnings are generated by `tempo2` and are nothing to worry about...)

In [7]:
psr.toas / 24 / 3600

array([53355.88885866, 53355.88885878, 53355.88885886, ...,
       57933.4178968 , 57933.41789684, 57933.41789688])

In [8]:
psr.toaerrs

array([1.107e-06, 3.720e-07, 7.950e-07, ..., 1.018e-06, 7.290e-07,
       5.200e-07])

In [9]:
psr.residuals

array([ 2.05402358e-05,  1.98079570e-05,  2.19405660e-05, ...,
       -7.09092625e-06, -5.62472991e-06, -5.84097656e-06])

In [10]:
psr.flags

{'fe': array(['430', '430', '430', ..., '430', '430', '430'], dtype='<U32'),
 'be': array(['ASP', 'ASP', 'ASP', ..., 'PUPPI', 'PUPPI', 'PUPPI'], dtype='<U32'),
 'f': array(['430_ASP', '430_ASP', '430_ASP', ..., '430_PUPPI', '430_PUPPI',
        '430_PUPPI'], dtype='<U32'),
 'bw': array(['4', '4', '4', ..., '1.562', '1.562', '1.562'], dtype='<U32'),
 'tobs': array(['902.19', '902.19', '902.19', ..., '1200.2', '1200.2', '1200.2'],
       dtype='<U32'),
 'tmplt': array(['J2317+1439.430.PUPPI.9y.x.sum.sm',
        'J2317+1439.430.PUPPI.9y.x.sum.sm',
        'J2317+1439.430.PUPPI.9y.x.sum.sm', ...,
        'J2317+1439.430.PUPPI.9y.x.sum.sm',
        'J2317+1439.430.PUPPI.9y.x.sum.sm',
        'J2317+1439.430.PUPPI.9y.x.sum.sm'], dtype='<U32'),
 'gof': array(['1.07', '1.04', '1.14', ..., '1.14', '1.03', '1.54'], dtype='<U32'),
 'nbin': array(['2048', '2048', '2048', ..., '2048', '2048', '2048'], dtype='<U32'),
 'nch': array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U32'),
 'chan': array([

## white noise model

The basic PTA white noise model contains **EFAC** and **EQUAD**.
EQUAD, $\mathcal{Q}$ is an additional error term added in quadrature to the timing uncertainty for each TOA, $\sigma$.
EFAC, $\mathcal{F}$, is an overall scale factor that multiplies the timing uncertainty for each TOA.
Both account for excess white noise that is not captured by the timing uncertainty.
In a perfect world if we understand the noise in our telescopes, EFAC would be $1$.
In practice it is often pretty close to $1$.

The basic white noise covariance matrix $\mathbb{N}$ is diagonal
$$\mathbb{N}_{ii} = \mathcal{F}^2\left({\sigma_i}^2 + \mathcal{Q}^2\right) $$

(note: this definition of WN uses the "tempo2 convention")

In practice each observing system may have different noise properties.
We define $\mathcal{F}_k$ and $\mathcal{Q}_k$, where $k$ denotes the observing system (e.g. L-band PUPPI or PDFB 20cm), so each system gets its own noise model.
This is referred to as **white noise per backend**.

* `white_signals.MeasurementNoise` implements this base white noise model
* `selelections.Selection` implements the backend (or any other) selection scheme
* the `parameter` module contains what we'll need to specify the parameter priors

In [11]:
from enterprise.signals import white_signals
from enterprise.signals import selections
from enterprise.signals import parameter

### Construct a white noise "signal" with EFAC and EQUAD per backend
the priors are:
* EFAC $\rightarrow$ Uniform(0.1, 10)
* EQUAD $\rightarrow$ LogUniform($10^{-8.5}, 10^{-5}$) sec
  * $\log_{10}$(EQUAD) $\rightarrow$ Uniform(-8.5, -5)

In [12]:
# define model parameters
efac = parameter.Uniform(0.1, 10)
equad = parameter.Uniform(-8.5, -5)

In [13]:
# use built in backend selection
backend = selections.Selection(selections.by_backend)

In [14]:
# make white noise "signal"
wn = white_signals.MeasurementNoise(efac=efac, log10_t2equad=equad, selection=backend)

The NANOGrav 12.5yr dataset used **channelized TOAs**, breaking a single observation into many TOAs for each radio frequency channel.  To account for jitter noise, which is highly correlated in all TOAs from the same observation, we use the ECORR model.

This makes the whitenoise covariance matrix, $\mathbb{N}$, block diagonal, where each block groups all of the TOAs from the same observation.

### Construct a per backend ECORR "signal"
prior:
* ECORR $\rightarrow$ LogUniform($10^{-8.5}, 10^{-5}$) sec
 * $\log_{10}$(ECORR) $\rightarrow$ Uniform(-8.5, -5)

When additional signals are added to a model in `enterprise` they are literally **added** to make the joint model:
```python
model = modA + modB
```

In [15]:
# define model parameters
ecorr = parameter.Uniform(-8.5, -5)

In [16]:
# make ecorr "signal" and add it to the existing WN signal
wn += white_signals.EcorrKernelNoise(log10_ecorr=ecorr, selection=backend)

## Gaussian process models

Gaussian process models are defined by a design matrix $\mathbb{T}$, a vector of basis coefficients $\vec{b}$, and a prior on the coefficients, $\mathbb{B}$.  For instance in the powerlaw red noise model the basis coefficients are the amplitude of various Fourier modes and the prior is the powerlaw which constrains these amplitudes to the right spectral shape.

The PTA likelihood **marginalizes** over the coefficients.
Only the GP prior affects the likelihood calculation.

In [17]:
from enterprise.signals import gp_signals
from enterprise.signals import gp_priors

### Construct a Fourier basis GP model for red noise and GWB
Both signals will use the `gp_signals.FourierBasisGP` class, in order to differentiate them we will pass the GWB signal a name.

prior:
* $\log_{10}(A_\mathrm{RN}) \rightarrow$ Uniform(-20, -11)
* $\gamma_\mathrm{RN} \rightarrow$ Uniform(0, 7)


* $\log_{10}(A_\mathrm{GWB}) \rightarrow$ Uniform(-18, -13)
* $\gamma_\mathrm{GWB} = 13/3$, constant (for SMBHB background)

We can also pass a name to `Parameter` classes, which tells them not to generate a common parameter for all pulsars, rather than a new one for each.  This is important for GWB parameters.

In [18]:
# define RN model parameters
rn_logA = parameter.Uniform(-20, -11)
rn_gam = parameter.Uniform(0, 7)

In [19]:
# define powerlaw for GP prior
powlaw = gp_priors.powerlaw(log10_A=rn_logA, gamma=rn_gam)

In [20]:
# make RN signal
rn = gp_signals.FourierBasisGP(
    powlaw,
    components=30,
)

In [21]:
# define GWB model parameters (don't forget to pass each a name)
gw_logA = parameter.Uniform(-18, -13)("gw_log10A")
gw_gam = parameter.Constant(13/3)("gw_gamma")

In [22]:
# define powerlaw for GP prior using GWB parameters
powlaw_gw = gp_priors.powerlaw(log10_A=gw_logA, gamma=gw_gam)

In [23]:
# make GWB signal (don't forget to name it)
gw = gp_signals.FourierBasisGP(
    powlaw_gw,
    components=30,
    name="gw",
)

In [24]:
gw_gam

gw_gamma:Constant=4.333333333333333

### instantiate a built in gp signal object for the timing model
There are two implementations of the linear timing model:

* `gp_signals.TimingModel`
* `gp_signals.MarginalizingTimingModel`

Each can take an option to use an SVD, which helps stablize the matrix when the timing model is poorly constrained.

In [25]:
# make the linear timing model signal
tm = gp_signals.TimingModel(use_svd=True)

## instantiate a `PTA` and compute the log-likelihood

Remember a model is the literal sum of its parts.
When we add `Signal` objects together we get a `SignalCollection` object.

The `enterprise` `SignalCollection` is a class factory.
It acts like a function that takes a `Pulsar` object as its input in order to apply that model to that pulsar
and returns an instantiated class instance.

The `signal_base.PTA` object can take either a single, instantiated pulsar model or a list of several pulsar models.
To do a single pulsar noiserun we will use just this one pulsar.

In [26]:
from enterprise.signals import signal_base

In [27]:
# add together the signals
sig = tm + wn + rn + gw

In [28]:
# make a PTA object
pta = signal_base.PTA(sig(psr))

## generate a random point in the model domain and calculate the likelihood and prior.

Each `enterprise` parameter object comes with its own `.sample` method, which draws a random sample from the prior distribution.
We can generate a point in the domain by sampling each parameter in turn.

`PTA.get_lnlikelihood` and `PTA.get_lnprior` can take an array-like input for the parameter vector or a dictionary.  Lets make a dictionary, whose keys are the parameter names and values are the random samples.

In [29]:
# make a parameter vector as a dictionary
p0 = {pp.name:pp.sample() for pp in pta.params}

In [30]:
# calculate logL and logPr
pta.get_lnlikelihood(p0), pta.get_lnprior(p0)

(KernelMatrix(104292.9146352), -29.742876109482033)

The `PTA` object contains all of the other objects that went into making it, including `Parameter`s and `Signal`s.

Let's look at what's in there...

### take a look at the output of each:
* `PTA.signals`
* `PTA.params`
* `PTA.param_names`
* `PTA.pulsars`
* `PTA.pulsarmodels`

In [31]:
pta.signals

{'J2317+1439_linear_timing_model_svd': <Enterprise Signal object linear_timing_model_svd[]>,
 'J2317+1439_measurement_noise': <Enterprise Signal object measurement_noise[J2317+1439_327_ASP_efac, J2317+1439_327_ASP_log10_t2equad, J2317+1439_327_PUPPI_efac, J2317+1439_327_PUPPI_log10_t2equad, J2317+1439_430_ASP_efac, J2317+1439_430_ASP_log10_t2equad, J2317+1439_430_PUPPI_efac, J2317+1439_430_PUPPI_log10_t2equad, J2317+1439_L-wide_PUPPI_efac, J2317+1439_L-wide_PUPPI_log10_t2equad]>,
 'J2317+1439_ecorr_sherman-morrison': <Enterprise Signal object ecorr_sherman-morrison[J2317+1439_327_ASP_log10_ecorr, J2317+1439_327_PUPPI_log10_ecorr, J2317+1439_430_ASP_log10_ecorr, J2317+1439_430_PUPPI_log10_ecorr, J2317+1439_L-wide_PUPPI_log10_ecorr]>,
 'J2317+1439_red_noise': <Enterprise Signal object red_noise[J2317+1439_red_noise_log10_A, J2317+1439_red_noise_gamma]>,
 'J2317+1439_gw': <Enterprise Signal object gw[gw_log10A]>}

In [32]:
pta.params

[J2317+1439_327_ASP_efac:Uniform(pmin=0.1, pmax=10),
 J2317+1439_327_ASP_log10_ecorr:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_327_ASP_log10_t2equad:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_327_PUPPI_efac:Uniform(pmin=0.1, pmax=10),
 J2317+1439_327_PUPPI_log10_ecorr:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_327_PUPPI_log10_t2equad:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_430_ASP_efac:Uniform(pmin=0.1, pmax=10),
 J2317+1439_430_ASP_log10_ecorr:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_430_ASP_log10_t2equad:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_430_PUPPI_efac:Uniform(pmin=0.1, pmax=10),
 J2317+1439_430_PUPPI_log10_ecorr:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_430_PUPPI_log10_t2equad:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_L-wide_PUPPI_efac:Uniform(pmin=0.1, pmax=10),
 J2317+1439_L-wide_PUPPI_log10_ecorr:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_L-wide_PUPPI_log10_t2equad:Uniform(pmin=-8.5, pmax=-5),
 J2317+1439_red_noise_gamma:Uniform(pmin=0, pmax=7),
 J2317+1439_red_noise_log10_A:Unifo

In [33]:
pta.param_names

['J2317+1439_327_ASP_efac',
 'J2317+1439_327_ASP_log10_ecorr',
 'J2317+1439_327_ASP_log10_t2equad',
 'J2317+1439_327_PUPPI_efac',
 'J2317+1439_327_PUPPI_log10_ecorr',
 'J2317+1439_327_PUPPI_log10_t2equad',
 'J2317+1439_430_ASP_efac',
 'J2317+1439_430_ASP_log10_ecorr',
 'J2317+1439_430_ASP_log10_t2equad',
 'J2317+1439_430_PUPPI_efac',
 'J2317+1439_430_PUPPI_log10_ecorr',
 'J2317+1439_430_PUPPI_log10_t2equad',
 'J2317+1439_L-wide_PUPPI_efac',
 'J2317+1439_L-wide_PUPPI_log10_ecorr',
 'J2317+1439_L-wide_PUPPI_log10_t2equad',
 'J2317+1439_red_noise_gamma',
 'J2317+1439_red_noise_log10_A',
 'gw_log10A']

In [34]:
pta.pulsars

['J2317+1439']

In [35]:
pta.pulsarmodels

[<Enterprise SignalCollection object J2317+1439: linear_timing_model_svd, measurement_noise, ecorr_sherman-morrison, red_noise, gw>]

The `PTA.summary` method outputs some information about the `PTA` object.
It's useful to print it or save it to file to keep track of things.

### print the output of `PTA.summary`

In [36]:
print(pta.summary())

enterprise v3.3.1,  Python v3.9.13

Signal Name                              Signal Class                   no. Parameters      
J2317+1439_linear_timing_model_svd       TimingModel                    0                   

params:
__________________________________________________________________________________________
J2317+1439_measurement_noise             MeasurementNoise               10                  

params:
J2317+1439_327_ASP_efac:Uniform(pmin=0.1, pmax=10)                                        
J2317+1439_327_ASP_log10_t2equad:Uniform(pmin=-8.5, pmax=-5)                              
J2317+1439_327_PUPPI_efac:Uniform(pmin=0.1, pmax=10)                                      
J2317+1439_327_PUPPI_log10_t2equad:Uniform(pmin=-8.5, pmax=-5)                            
J2317+1439_430_ASP_efac:Uniform(pmin=0.1, pmax=10)                                        
J2317+1439_430_ASP_log10_t2equad:Uniform(pmin=-8.5, pmax=-5)                              
J2317+1439_430_PUPPI_efac:Unif

## What's goes into the likelihood?

The full covariance matrix $\mathbb{C}$ is $N_\mathrm{TOA}\times N_\mathrm{TOA}$, which is a nightmare to directly invert.
There's a lot of fancy linear algebraic manipulations that build $\mathbb{C}^{-1}$ out of more manageable parts.

### T-matrix

The $\mathbb{T}$ matrix is $N_\mathrm{TOA} \times N_\mathrm{coef}$, where $N_\mathrm{coef}$ is the total number of GP coefficients in all GP models.  The $\mathbb{T}$ matrix is the *design matrix* for the **GP basis**.  We can access it with the `PTA.get_basis` method.

The GW and RN models share common Fourier basis with $60$ coefficients ($30$ sine amplitudes & $30$ cosine).

J2317 has $230$ timing model parameters!
There are $19$ "traditional" timing model parameters:
* spin: $(2)$: F0, F1
* astrometric $(5)$: ELONG, ELAT, PMELONG, PMELAT, PX
* binary ELL1H $(7)$: A1, PB, TASC, EPS1, EPS2, H3, H4
* FD $(3)$
* jumps $(2)$

But the DMX model which has $211$ bins!

This makes $N_\mathrm{coef} = 290$.

In [37]:
# check the number of TOAs
psr.toas.shape

(9835,)

In [38]:
# check the shape of the the "T-matrix"
np.shape(pta.get_basis())

(1, 9835, 290)

### N-matrix

The block-diagonal white noise covariance $\mathbb{N}$ matrix is accessed via `PTA.get_ndiag`.

It's not much to look at, because it is obscured as a special class that sets up the Sherman-Morrison matrix inversion scheme.

In [39]:
# check the output of the "N-matrix"
pta.get_ndiag(p0)

### B-matrix

The GP prior $\mathbb{B}$ matrix is can be broken out as:
$$
  \mathbb{B} =
    \begin{bmatrix}
    \infty & 0\\
    0 & \varphi
    \end{bmatrix},
$$
where $\infty$ is a diagonal matrix of infinities representing the improper, uniform prior on the linear timing model coefficients and $\varphi$ is the Fourier basis prior.
The Fourier modes are approximately orthogonal, so $\varphi$ is diagonal too.
This means the whole $\mathbb{B}$ matrix is diagonal and can be stored as a vector.

Since $\varphi$ is the non-trivial part of the $\mathbb{B}$ matrix, the two aren't always clearly distinguished...
In `enterprise` the `PTA.get_phi` and `PTA.get_phiinv` methods access the $\mathbb{B}$ matrix and its inverse.

In [40]:
#check the shape of the "B-matrix"
pta.get_phi(p0)[0].shape

(290,)

In [41]:
# frequencies
Tspan = psr.toas.max() - psr.toas.min()
np.arange(1, 31) / Tspan

array([2.52845454e-09, 5.05690908e-09, 7.58536362e-09, 1.01138182e-08,
       1.26422727e-08, 1.51707272e-08, 1.76991818e-08, 2.02276363e-08,
       2.27560909e-08, 2.52845454e-08, 2.78129999e-08, 3.03414545e-08,
       3.28699090e-08, 3.53983635e-08, 3.79268181e-08, 4.04552726e-08,
       4.29837272e-08, 4.55121817e-08, 4.80406362e-08, 5.05690908e-08,
       5.30975453e-08, 5.56259999e-08, 5.81544544e-08, 6.06829089e-08,
       6.32113635e-08, 6.57398180e-08, 6.82682726e-08, 7.07967271e-08,
       7.33251816e-08, 7.58536362e-08])

### other parts of the covariance matrix
Some other useful combinations of matrices are used in the $\mathbb{C}$ matrix inversion for the likelihood calculation
. For example `PTA.get_TNT` and `PTA.get_TNr`:

In [42]:
pta.get_TNT(p0)[0].shape

(290, 290)

In [43]:
pta.get_TNr(p0)[0].shape

(290,)

### s-vector
Our model doesn't have a deterministic signal, $\vec{s}$.  But if it did, we could find it in the `PTA` as `get_delay`.

In [44]:
# "s-vector"
pta.get_delay(p0)

[0]